name: ronda_patrimonial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  chopper: ^7.0.0
  flutter:
    sdk: flutter
  flutter_background_service: ^3.0.1
  objectbox: ^2.1.0
  objectbox_flutter_libs: any
  path: ^1.8.3
  path_provider: ^2.0.15
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter:
  uses-material-design: true
