// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/core/models/unit_model.dart';
import 'app/features/home/models/panic_alert_event_model.dart';
import 'app/features/home/models/patrol_event_model.dart';
import 'app/features/home/models/tag_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3087131332108098366),
      name: 'PanicAlertEventModel',
      lastPropertyId: const IdUid(3, 8440443800369935513),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5832780676944272820),
            name: 'panicAlertEventId',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 919228545884023648),
            name: 'unitId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8440443800369935513),
            name: 'eventDateTime',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 5745760903728289519),
      name: 'PatrolEventModel',
      lastPropertyId: const IdUid(4, 2571802167605091145),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8565743388301742838),
            name: 'patrolEventId',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1512964026652504034),
            name: 'unitId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7789797893567335538),
            name: 'tagId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2571802167605091145),
            name: 'eventDateTime',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 8262870305814255861),
      name: 'TagModel',
      lastPropertyId: const IdUid(4, 6500600897761070297),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4855903845281571095),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6413125767259976566),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5826872289631033800),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6500600897761070297),
            name: 'isActive',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 3095805658382075902),
      name: 'UnitModel',
      lastPropertyId: const IdUid(4, 3589584843093084745),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(3, 859114261221241486),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(4, 3589584843093084745),
            name: 'title',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 3095805658382075902),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(1, 3447508778015872074),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [1142397732133121684, 2677158136543875206],
      retiredRelationUids: const [3447508778015872074],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    PanicAlertEventModel: EntityDefinition<PanicAlertEventModel>(
        model: _entities[0],
        toOneRelations: (PanicAlertEventModel object) => [],
        toManyRelations: (PanicAlertEventModel object) => {},
        getId: (PanicAlertEventModel object) => object.panicAlertEventId,
        setId: (PanicAlertEventModel object, int id) {
          object.panicAlertEventId = id;
        },
        objectToFB: (PanicAlertEventModel object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.panicAlertEventId);
          fbb.addInt64(1, object.unitId);
          fbb.addInt64(2, object.eventDateTime.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.panicAlertEventId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final panicAlertEventIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final unitIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final eventDateTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final object = PanicAlertEventModel(
              panicAlertEventId: panicAlertEventIdParam,
              unitId: unitIdParam,
              eventDateTime: eventDateTimeParam);

          return object;
        }),
    PatrolEventModel: EntityDefinition<PatrolEventModel>(
        model: _entities[1],
        toOneRelations: (PatrolEventModel object) => [],
        toManyRelations: (PatrolEventModel object) => {},
        getId: (PatrolEventModel object) => object.patrolEventId,
        setId: (PatrolEventModel object, int id) {
          object.patrolEventId = id;
        },
        objectToFB: (PatrolEventModel object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.patrolEventId);
          fbb.addInt64(1, object.unitId);
          fbb.addInt64(2, object.tagId);
          fbb.addInt64(3, object.eventDateTime.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.patrolEventId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final patrolEventIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final unitIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final tagIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final eventDateTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final object = PatrolEventModel(
              patrolEventId: patrolEventIdParam,
              unitId: unitIdParam,
              tagId: tagIdParam,
              eventDateTime: eventDateTimeParam);

          return object;
        }),
    TagModel: EntityDefinition<TagModel>(
        model: _entities[2],
        toOneRelations: (TagModel object) => [],
        toManyRelations: (TagModel object) => {},
        getId: (TagModel object) => object.id,
        setId: (TagModel object, int id) {
          object.id = id;
        },
        objectToFB: (TagModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final typeOffset = fbb.writeString(object.type);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, typeOffset);
          fbb.addBool(3, object.isActive);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final isActiveParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final object =
              TagModel(idParam, titleParam, typeParam, isActiveParam);

          return object;
        }),
    UnitModel: EntityDefinition<UnitModel>(
        model: _entities[3],
        toOneRelations: (UnitModel object) => [],
        toManyRelations: (UnitModel object) => {},
        getId: (UnitModel object) => object.id,
        setId: (UnitModel object, int id) {
          if (object.id != id) {
            throw ArgumentError('Field UnitModel.id is read-only '
                '(final or getter-only) and it was declared to be self-assigned. '
                'However, the currently inserted object (.id=${object.id}) '
                "doesn't match the inserted ID (ID $id). "
                'You must assign an ID before calling [box.put()].');
          }
        },
        objectToFB: (UnitModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          fbb.startTable(5);
          fbb.addInt64(2, object.id);
          fbb.addOffset(3, titleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = UnitModel(idParam, titleParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [PanicAlertEventModel] entity fields to define ObjectBox queries.
class PanicAlertEventModel_ {
  /// see [PanicAlertEventModel.panicAlertEventId]
  static final panicAlertEventId =
      QueryIntegerProperty<PanicAlertEventModel>(_entities[0].properties[0]);

  /// see [PanicAlertEventModel.unitId]
  static final unitId =
      QueryIntegerProperty<PanicAlertEventModel>(_entities[0].properties[1]);

  /// see [PanicAlertEventModel.eventDateTime]
  static final eventDateTime =
      QueryIntegerProperty<PanicAlertEventModel>(_entities[0].properties[2]);
}

/// [PatrolEventModel] entity fields to define ObjectBox queries.
class PatrolEventModel_ {
  /// see [PatrolEventModel.patrolEventId]
  static final patrolEventId =
      QueryIntegerProperty<PatrolEventModel>(_entities[1].properties[0]);

  /// see [PatrolEventModel.unitId]
  static final unitId =
      QueryIntegerProperty<PatrolEventModel>(_entities[1].properties[1]);

  /// see [PatrolEventModel.tagId]
  static final tagId =
      QueryIntegerProperty<PatrolEventModel>(_entities[1].properties[2]);

  /// see [PatrolEventModel.eventDateTime]
  static final eventDateTime =
      QueryIntegerProperty<PatrolEventModel>(_entities[1].properties[3]);
}

/// [TagModel] entity fields to define ObjectBox queries.
class TagModel_ {
  /// see [TagModel.id]
  static final id = QueryIntegerProperty<TagModel>(_entities[2].properties[0]);

  /// see [TagModel.title]
  static final title =
      QueryStringProperty<TagModel>(_entities[2].properties[1]);

  /// see [TagModel.type]
  static final type = QueryStringProperty<TagModel>(_entities[2].properties[2]);

  /// see [TagModel.isActive]
  static final isActive =
      QueryBooleanProperty<TagModel>(_entities[2].properties[3]);
}

/// [UnitModel] entity fields to define ObjectBox queries.
class UnitModel_ {
  /// see [UnitModel.id]
  static final id = QueryIntegerProperty<UnitModel>(_entities[3].properties[0]);

  /// see [UnitModel.title]
  static final title =
      QueryStringProperty<UnitModel>(_entities[3].properties[1]);
}
